POST  http://localhost:9000/login
Content-Type: application/json

{
  "username" : "Thabane",
  "password": "ngobe"
}

###

POST  http://localhost:9000/createAccount
Content-Type: application/json

{
  "username": "Thabane",
  "password": "ngobe"
}

###

POST http://localhost:9000/saveResource
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRoYWJhbmUiLCJwYXNzd29yZCI6IiQyYiQxMCR0S21OWkRjeWZaZHdrQUJQVjR3bGlPMUg5WkJYSmxnL0ZmZnJuT2J6S281Sk9Gek8uU0JsLiIsImlhdCI6MTczNDUzOTUwN30.0-WxekHjwc_36Om378xNiTkowzyGuZBoaL2LnjKLZZw

{
  "url" : "https://www.youtube.com/watch?v=sr7noqbtuSU"
}


###
GET http://localhost:9000/resources
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRoYWJhbmUiLCJwYXNzd29yZCI6IiQyYiQxMCR0S21OWkRjeWZaZHdrQUJQVjR3bGlPMUg5WkJYSmxnL0ZmZnJuT2J6S281Sk9Gek8uU0JsLiIsImlhdCI6MTczNDUzOTUwN30.0-WxekHjwc_36Om378xNiTkowzyGuZBoaL2LnjKLZZw